startup-32/Delete Members section
liip/thinkspace pull request #11
Opened 2018-08-09 12:46 UTC by renatomoor

2018-08-09 13:06 UTC, T4m commented on .gitignore
> +!node_modules/kanbasu
Je pense que ces deux nouvelle lignes au fichier `.gitignore` ne sont pas nécessaire.

2018-08-09 13:08 UTC, T4m commented on README.md
> +* Node modules are into git repository because jekyll needs them to build.
Très bien :+1:

2018-08-09 13:20 UTC, T4m requested changes
Il faut aussi supprimer l'inclusion de sections/members ici: `assets/main.scss:29`. Sinon ça plante au démarrage du server.

2018-08-09 13:46 UTC, sirgix commented on .gitignore
> +!node_modules/kanbasu
@T4m Pas tout à fait... Le truc c'est que si tu npm install il prend une versions plus récente qui a des dépendances qu'on ne veut pas gitter. Donc il faudrait fixer kanbasu à la 1.2.2 pour que ça marche. Mais du coup, si on gitte node_modules et qu'on bloque la version il n'y a plus aucun intérêt d'avoir npm pour ça, autant ne garder plus que les fichiers de kanbasu dont on a besoin non?

2018-08-09 14:53 UTC, T4m commented on .gitignore
> +!node_modules/kanbasu
SVP, supprimer ces deux lignes, en tout cas pour cette story.

2018-08-09 14:54 UTC, T4m approved these changes

2018-08-09 15:21 UTC, renatomoor commented on .gitignore
> +!node_modules/kanbasu
@T4m Done!

2018-08-13 09:10 UTC, T4m requested changes

2018-08-13 09:10 UTC, T4m commented on .gitignore
> +.sass-cache
Je n'ai pas l'impression que l'ajout au `.gitignore` de `.sass-cache` soit en lien avec la suppression de la section membres. Mais je me trompe peut-être. Peux-tu m'expliquer ?

2018-08-13 09:33 UTC, renatomoor commented on .gitignore
> +.sass-cache
Cette comme ça a la base: https://github.com/liip/thinkspace/blob/gh-pages/.gitignore

2018-08-13 13:54 UTC, T4m commented on .gitignore
> +.sass-cache
J'ai compris, c'est uniquement un problème de retour à la ligne. Est-ce que tu peux ajouter un retour à la ligne à la fin du fichier ?

Normalement, ce fichier ne devrait plus apparaître dans cette pull request.

2018-08-13 14:29 UTC, renatomoor commented on .gitignore
> +.sass-cache
Done !

2018-08-14 07:31 UTC, merged